### ISSUE TITLE
public + project filter flags do not work together

### ISSUE THREAD

**Issue by asalic** [chaimeleon-eu/dataset-service#1]
Steps:
1. got to https://chaimeleon-test.grycap.i3m.upv.es/dataset-service/datasets?invalidated=false
2. select project CHAIMELEON
3. click on "-" Published flag in the filters box

test2randomstudies should not appear in the list.

**Comment by Palollo** [comment]
It seems the issue only occurred when the user was not logged in.
It is fixed now.
