### ISSUE TITLE
Change the way dataset explorer is uploaded to the server via /api/set-ui' (maintain the current approach too

### ISSUE THREAD

**Issue by asalic** [chaimeleon-eu/dataset-service#4]
maybe accept a body in the post containing the zip instead of the url where the zip is located. this way we avoid the need of additional open ports. The current way of getting the zip should be maintained

**Comment by Palollo** [comment]
There is a second method uploading directly the ZIP file in the body: 
https://github.com/chaimeleon-eu/dataset-service/blob/main/README.md#only-for-developers-set-or-update-the-web-ui
